In [5]:
from data import CWTR


from data import CWTR_SUM, DOTACION
#DF = CWTR_SUM[CWTR_SUM["legajo"].eq(6066825)]

DF = CWTR_SUM.head(30)
DF

     legajo   CCn  mes     importe
0   6000002  /111    1   323617.99
1   6000002  /111    2  1404173.92
2   6000002  /111    3   351100.00
3   6000002  /111    4   353440.65
4   6000002  /111    5   351100.00
5   6000002  /111    6   911460.00
6   6000002  /111    7   193340.01
7   6000002  /111    8   479676.68
8   6000002  /111    9   586100.00
9   6000002  /111   10   586100.00
10  6000002  /111   11   586100.00
11  6000002  /111   12  1054950.00
12  6000002  /124    1   144132.00
13  6000002  /124    3     3850.00
14  6000002  /124    4     4950.00
15  6000002  /124    5     7700.00
16  6000002  /124    6     6050.00
17  6000002  /124    7     1100.00
18  6000002  /124    8     7150.00
19  6000002  /124    9     6600.00
20  6000002  /124   10     6600.00
21  6000002  /124   11     6050.00
22  6000002  /124   12     3300.00
23  6000002  /321    1    33825.04
24  6000002  /321    2    34991.42
25  6000002  /321    3    38621.00
26  6000002  /321    4    37333.63
27  6000002  /321    5    38621.00
28  6000002  /321    6    36315.58
29  6000002  /321    7    17668.76

In [5]:
from empleado import Empleado, NominasCWTR


pau = Empleado(6066825)
pau.__dict__

{'legajo': 6066825, 'nombre': 'GRIFFA,MARIA PAULA'}

In [7]:
from parametrizacion.conceptos import ParamConceptos
a = ParamConceptos()

concepto_suma_base = a.listar("BaseTramos","+")
concepto_resta_base = a.listar("BaseTramos","-")

['/S02']

In [3]:
from helpers.bases import tabla
#tabla("prorrateos").head(30)

from remuneraciones.prorrateos import *
p = Prorrateos()
p.prorrateados().head(50)

,index,legajo,CCn,nombre,importe,mes,mes_pago,origen
0,1,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,1,1,fx
1,2,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,2,1,fx
2,3,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,3,1,fx
3,4,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,4,1,fx
4,5,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,5,1,fx
5,6,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,6,1,fx
6,7,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,7,1,fx
7,8,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,8,1,fx
8,9,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,9,1,fx
9,10,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,10,1,fx
10,11,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,11,1,fx
11,12,6000002,#/V75,[Proporcional] Diferencia plus vacacion.,1356.889167,12,1,fx
12,14,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,4,4,fx
13,15,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,5,4,fx
14,16,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,6,4,fx
15,17,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,7,4,fx
16,18,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,8,4,fx
17,19,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,9,4,fx
18,20,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,10,4,fx
19,21,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,11,4,fx
20,22,6000002,#1256,[Proporcional] Plus por vacaciones,260.074444,12,4,fx
21,24,6000002,#1256,[Proporcional] Plus por vacaciones,7356.381429,6,6,fx
22,25,6000002,#1256,[Proporcional] Plus por vacaciones,7356.381429,7,6,fx
23,26,6000002,#1256,[Proporcional] Plus por vacaciones,7356.381429,8,6,fx
24,27,6000002,#1256,[Proporcional] Plus por vacaciones,7356.381429,9,6,fx
25,28,6000002,#1256,[Proporcional] Plus por vacaciones,7356.381429,10,6,fx
26,29,6000002,#1256,[Proporcional] Plus por vacaciones,7356.381429,11,6,fx
27,30,6000002,#1256,[Proporcional] Plus por vacaciones,7356.381429,12,6,fx
28,32,6000002,#1256,[Proporcional] Plus por vacaciones,552.400000,8,8,fx
29,33,6000002,#1256,[Proporcional] Plus por vacaciones,552.400000,9,8,fx
30,34,6000002,#1256,[Proporcional] Plus por vacaciones,552.400000,10,8,fx
31,35,6000002,#1256,[Proporcional] Plus por vacaciones,552.400000,11,8,fx
32,36,6000002,#1256,[Proporcional] Plus por vacaciones,552.400000,12,8,fx
33,38,6000002,#1256,[Proporcional] Plus por vacaciones,1324.190000,6,6,fx
34,39,6000002,#1256,[Proporcional] Plus por vacaciones,1324.190000,7,6,fx
35,40,6000002,#1256,[Proporcional] Plus por vacaciones,1324.190000,8,6,fx
36,41,6000002,#1256,[Proporcional] Plus por vacaciones,1324.190000,9,6,fx
37,42,6000002,#1256,[Proporcional] Plus por vacaciones,1324.190000,10,6,fx
38,43,6000002,#1256,[Proporcional] Plus por vacaciones,1324.190000,11,6,fx
39,44,6000002,#1256,[Proporcional] Plus por vacaciones,1324.190000,12,6,fx
40,46,6000002,#1256,[Proporcional] Plus por vacaciones,82.934000,8,8,fx
41,47,6000002,#1256,[Proporcional] Plus por vacaciones,82.934000,9,8,fx
42,48,6000002,#1256,[Proporcional] Plus por vacaciones,82.934000,10,8,fx
43,49,6000002,#1256,[Proporcional] Plus por vacaciones,82.934000,11,8,fx
44,50,6000002,#1256,[Proporcional] Plus por vacaciones,82.934000,12,8,fx
45,52,6000002,#1258,[Proporcional] Plus Rem.Var.p/vacaciones,0.000000,4,4,fx
46,53,6000002,#1258,[Proporcional] Plus Rem.Var.p/vacaciones,0.000000,5,4,fx
47,54,6000002,#1258,[Proporcional] Plus Rem.Var.p/vacaciones,0.000000,6,4,fx
48,55,6000002,#1258,[Proporcional] Plus Rem.Var.p/vacaciones,0.000000,7,4,fx
49,56,6000002,#1258,[Proporcional] Plus Rem.Var.p/vacaciones,0.000000,8,4,fx

In [29]:
for i in range(1,9):
    print(i)

1
2
3
4
5
6
7
8

In [6]:
from deducciones.incremental.tablas_tramo2 import TablasTramo2


TablasTramo2.deduccion(2,250000)

17024.0

In [9]:
from deducciones.incremental.calculo import *
BASES_DEDUC_INCREM.head(30)
#df[df["CCn"].eq("/111")]
BASES_DEDUC_INCREM.head(50)

     legajo  mes  BaseTramos
0   6000002    1   466593.92
1   6000002    2  1405581.67
2   6000002    3   359751.07
3   6000002    4   363686.19
4   6000002    5   363361.69
5   6000002    6   705979.09
6   6000002    7   213520.60
7   6000002    8   493782.79
8   6000002    9   600794.59
9   6000002   10   599771.35
10  6000002   11   601885.49
11  6000002   12   717865.90
12  6000009    1   295457.25
13  6000009    2   208572.55
14  6000009    3   193848.02
15  6000009    4   230493.70
16  6000009    5   246092.17
17  6000009    6   267862.61
18  6000009    7   298932.97
19  6000009    8   351847.36
20  6000009    9   386237.31
21  6000009   10   463265.01
22  6000009   11   429796.04
23  6000009   12   502665.54
24  6000010    1   320720.98
25  6000010    2   659090.40
26  6000010    3   288991.47
27  6000010    4   292469.47
28  6000010    5   292785.10
29  6000010    6   332602.03
30  6000010    7   370992.85
31  6000010    8   352961.82
32  6000010    9   419954.22
33  6000010   10   425853.79
34  6000010   11   425933.09
35  6000010   12   485374.92
36  6000011    1   280536.65
37  6000011    2   510562.32
38  6000011    3   243398.75
39  6000011    4   241991.93
40  6000011    5   247069.33
41  6000011    6   288161.56
42  6000011    7   287589.40
43  6000011    8   302110.84
44  6000011    9   352832.55
45  6000011   10   368787.55
46  6000011   11   384422.95
47  6000011   12   425148.64
48  6000013    1   273783.43
49  6000013    2   513575.22

In [32]:
from data import CWTR
CWTR[CWTR["legajo"].eq(6114231)]

         legajo   CCn    periodo fecha_pago  mes  importe
483548  6114231  /351 2022-12-31 2022-12-30   12  1414.91
483549  6114231  /361 2022-12-31 2022-12-30   12  1414.91

In [12]:
PAU = 6066825
from deducciones.incremental.calculo import *
from empleado import *

DeduccionEspecial.norma_aplicable(7)
prueba2 = DeduccionEspecial.obtener_rem_mes(PAU,2)
prueba2

# for i in range(1,13):
#     print(DeduccionEspecial.obtener_tramo(Empleado(PAU),i))

421239.19

In [12]:
dot = DOTACION["legajo"]
dot

0       6000002
1       6000009
2       6000010
3       6000011
4       6000013
         ...
3061    6114229
3062    6114231
3063    6114233
3064    6114235
3065    6114237
Name: legajo, Length: 3066, dtype: int64